### ISSUE TITLE
Upgrading gear in the smithing table doesn't consume the correct amount of resources

### ISSUE THREAD

**Issue by pajicadvance** [sisby-folk/tinkerers-smithing#12]
When upgrading gear in the smithing table, only one resource gets used no matter how many you put in the upgrade slot, for example, when upgrading an iron pickaxe to a diamond pickaxe with 3 diamonds, only 1 diamond will be used, but the resulting diamond pickaxe will have full durability:

![image](https://github.com/sisby-folk/tinkerers-smithing/assets/32738446/d700ea4b-57bc-494e-9037-b3459d561a28)
results in
![image](https://github.com/sisby-folk/tinkerers-smithing/assets/32738446/a5b7006e-9cd9-4bf9-9b4f-a130fb1c81ad)

This happens for any piece of gear of any material.

MC 1.20.1, mod version 2.2.8, Quilt 0.19.2

**Comment by sisby-folk** [comment]
can you confirm that this happens both in regular click and shift click, and in isolation? we've had this bug before and I thought it was fixed.

**Comment by pajicadvance** [comment]
> can you confirm that this happens both in regular click and shift click,

Happens in both cases.

> and in isolation?

The only two mods I have installed for this test is this one and QFAPI.

**Comment by sisby-folk** [comment]
Alright! isolating this now

 - Works in 1.19.2
 - Works in 1.19.3
 - Broken in 1.19.4
 - Broken in 1.20/.1

**Comment by sisby-folk** [comment]
The issue in 1.19.4 is caused by the fact that the mixin needs to target LegacySmithingScreenHandler and it's not (1.19.4 is a very weird version), fixed that one

**Comment by sisby-folk** [comment]
1.20/1 issue was due to improper slot selection - fixed as well. going to clean this up and do a release.

**Comment by sisby-folk** [comment]
Released as [2.2.11](https://modrinth.com/mod/tinkerers-smithing/version/2.2.11+1.20), let me know if the issue persists.
