### ISSUE TITLE
Mod is said to be optional on client, but clients are kicked if present on the server only

### ISSUE THREAD

**Issue by ghost** [sisby-folk/tinkerers-smithing#13]
Quilt 1.20.1
Only mods on server are Tinkerers Smithing and QSL, client has nothing.
![image](https://github.com/sisby-folk/tinkerers-smithing/assets/100542617/abb30ef2-2dec-4815-ba74-b56448d017c4)
![2023-07-25_16 23 15](https://github.com/sisby-folk/tinkerers-smithing/assets/100542617/ce221138-fe7c-427a-81c1-5265786d9cdf)

**Comment by sisby-folk** [comment]
huh, fair enough, we'll look into how we might be able to make synchronizing those recipe types optional.

**Comment by sisby-folk** [comment]
Should be solved in 2.4.0
