### ISSUE TITLE
Forge 1.20.1

### ISSUE THREAD

**Issue by spunchbop121** [sisby-folk/tinkerers-smithing#15]
Mods:
backpacked-forge-1.20.1-2.2.3.jar
catalogue-forge-1.20.1-1.7.1.jar
emi-1.0.19+1.20.1+forge.jar
framework-forge-1.20.1-0.6.11.jar
jei-1.20.1-forge-15.2.0.25.jar
tinkerers_smithing-2.3.0-connector+1.20.jar

https://ibb.co/nQNzj3R

Mod just doesn't work, idk why

**Comment by sisby-folk** [comment]
did you uh, figure it out
