### ISSUE TITLE
Anvil de-working does not work on 1.20.1

### ISSUE THREAD

**Issue by Similacrest** [sisby-folk/tinkerers-smithing#17]
Steps to reproduce:
1. Set up an isolated instance (Quilt singleplayer with TSmith 2.4.0 and QFAPI 7.1.2; game version 1.19.2 (working) and 1.20.1 (broken))
2. Combine enchanted iron pickaxes a bunch of times
3. Switch to Survival
4. Try to put the pickaxe and netherite scraps in the anvil.
Expected result: deworking occurs ![1.19.2](https://github.com/sisby-folk/tinkerers-smithing/assets/2362022/0be5f323-f028-4409-b431-fce9521b339a)
Actual result: recipe does not seem to exist
![1.20.1](https://github.com/sisby-folk/tinkerers-smithing/assets/2362022/4c7a568a-04d5-4fcb-b6c1-d2e293708940)

**Comment by sisby-folk** [comment]
Oh hey great timing, we were just about to write this off as an non-fix-worthy incompatibility when we encountered it in the blanketcon modpack - we'll get a fix out within 72 hours :P

**Comment by sisby-folk** [comment]
Fixed in 2.4.1 - we had changed the slot indexes for our anvil mixin, seemingly getting them confused with the smithing table changes, where there was none to the anvil.
