### ISSUE TITLE
Broken Tools still apply their enchantments when using them to break blocks

### ISSUE THREAD

**Issue by Similacrest** [sisby-folk/tinkerers-smithing#18]
A low-priority peeve of mine. Have not tested this with armor yet.

Steps to reproduce:
1. Enchant an iron pick with Silk Touch 
2. Break the pick (throw it and run `/data modify @e[type=item,limit=1] Item.tag.Damage set value 248`, then mine a few more blocks)
3. Break a non-`#mineable/pickaxe`  block such as grass

Expected result:
block is not broken at all, or broken as if by hand, because the tool is broken
Actual result:
grass block is broken as if a non-broken silk touch tool was used

**Comment by sisby-folk** [comment]
Solved on 2.5.1
