### ISSUE TITLE
About Curse of Binding

### ISSUE THREAD

**Issue by FireSparkC** [sisby-folk/tinkerers-smithing#19]
The broken Curse of Binding Equipment has always occupied the equipment slot.If such equipment is equipped, there is no way to replace it.

**Comment by sisby-folk** [comment]
Genuinely not sure how to solve this one - Tinkerer's smithing expects that you can't lose enchanted items, but curse of binding expects that you can't keep them. "remove curse of binding entirely" seems too dramatic, but it's the only thing that would satisfy both properties.

**Comment by FireSparkC** [comment]
> Genuinely not sure how to solve this one - Tinkerer's smithing expects that you can't lose enchanted items, but curse of binding expects that you can't keep them. "remove curse of binding entirely" seems too dramatic, but it's the only thing that would satisfy both properties.

I think you can try adding a more expensive consumable to destroy Broken Equipment or to eliminate the binding curses.

**Comment by sisby-folk** [comment]
I think the solution we're going to implement is that the binding curse doesn't work while the equipment is broken, and starts working again once it's repaired. ergo binding doesn't allow you to _modify_ equipment for the full duration of its durability. This may cause issues for some mapmakers, but i'm happy with it.

**Comment by FireSparkC** [comment]
> I think the solution we're going to implement is that the binding curse doesn't work while the equipment is broken, and starts working again once it's repaired. ergo binding doesn't allow you to _modify_ equipment for the full duration of its durability. This may cause issues for some mapmakers, but i'm happy with it.

GOOD IDEA!

**Comment by sisby-folk** [comment]
Done in 2.5.1, credit to aquaholic for the idea - sorted.
