### ISSUE TITLE
[1.18.2] Need nbtcrafting-2.2.4, repair function not working on 1.1.0+ (Backport request?)

### ISSUE THREAD

**Issue by ConqAra** [sisby-folk/tinkerers-smithing#20]
~~the logging is very annoying, making log files go up to 2MB. It seems its just complaining about the "%" in the data jsons. is there way for me to fix this or a workaround? maybe use "percent" instead of "%"... I really don't wanna bother you with such a outdated version but I'm mainly asking for help. An updated backport for 1.18.2 fabric would be incredible though. I'm just mainly looking for answers.~~

Edit: I decided to use an anti log-spam mod for now, but i guess i'll leave the 2.0 backport question here anyways. I'm just having trouble using the fabric 1.18.2 versions for my modpack. And now the durability reparing stopped working too on the smithing table?? It's odd because the upgrade works, just none of the repairs.
![image](https://github.com/sisby-folk/tinkerers-smithing/assets/76233356/5a528220-f8be-423e-b265-d931c09abece)

**Comment by ConqAra** [comment]
Found out I was using 1.1.0. problem fixed when I swapped to 1.0.1. Is the percentage thing still not compatible with the 2.2.3 version of nbt crafting im using?

**Comment by ConqAra** [comment]
Oh, im looking for the nbtcrafting-2.2.4 you made before. I can't find it anymore.

**Comment by sisby-folk** [comment]
The implementation of the modulo operator is covered by https://github.com/Siphalor/nbt-crafting/pull/133. 1.0.1 does not require it, 1.1.0 does.

We'll consider a 1.18.2 backport of 2.0 at some point.

**Comment by sisby-folk** [comment]
https://modrinth.com/mod/tinkerers-smithing/version/2.5.1+1.18
