### ISSUE TITLE
Recipes only work in singleplayer despite mod being installed on client and server.

### ISSUE THREAD

**Issue by TheD0ct0r101** [sisby-folk/tinkerers-smithing#27]
version: 1.17.1, 1.0.1 with NBT Crafting

I can turn an iron sword into a diamond sword in a smithing table, but on my server the smithing table just has an X in it, denying the recipe. The server is running the mods just fine.

**Comment by sisby-folk** [comment]
TSmithing 1.0 is purely a datapack - any issues like this are on NBT crafting's side.
