### ISSUE TITLE
[1.18.2] Option to disable broken feature? Incompatible with XP Storage Books

### ISSUE THREAD

**Issue by ConqAra** [sisby-folk/tinkerers-smithing#28]
Using [Xp Storage Mod](https://www.curseforge.com/minecraft/mc-mods/xp-storage) with tinkers smithing broken feature prevents the xp book from working when taking out levels from it. Since it uses a durability system, it going to 0 will disable the xp book and render it useless. Any way you could fix this or at least have a config to disable the broken feature in case its incompatible with certain mods like this one?

**Comment by sisby-folk** [comment]
Uhh, while adding configuration for blacklisting equipment from becoming "broken" is viable and we will, mods shouldn't use durability to represent something that isn't durability when they're mixed-side - just save the number under another nbt key and override the item bar step and tooltip methods.

**Comment by ConqAra** [comment]
Yeah idk why it decided to use durability, I just hope a system is made so you can blacklist certain items from being broken soon. I don't really see an alternative to use either. Thank you for the quick response and best of luck!

**Comment by sisby-folk** [comment]
feel free to report the issue to them as well! but yes we will be adding a blacklist system or similar.

**Comment by sisby-folk** [comment]
added as the tag `tinkerers_smithing:broken_blacklist` in 2.6
