### ISSUE TITLE
[1.20.1] Incompat with Spectrum

### ISSUE THREAD

**Issue by Aquaeyes** [sisby-folk/tinkerers-smithing#29]
[NCQKkfE.txt](https://github.com/sisby-folk/tinkerers-smithing/files/13903652/NCQKkfE.txt)

Crash is on world load o7o7

**Comment by sisby-folk** [comment]
easy infinite loop via mixin:

We check isDamageable during enchantment helpers:
![image](https://github.com/sisby-folk/tinkerers-smithing/assets/55819817/57ecbddb-003f-4db4-a462-ea9bea2d5077)

Spectrum checks enchantment helpers during isDamageable:
![image](https://github.com/sisby-folk/tinkerers-smithing/assets/55819817/6179ba67-3896-42a9-9563-24b625a6fcd0)

**Comment by OcrSu** [comment]
i have the same issue..
waiting for fixed update.
