### ISSUE TITLE
[1.20.1] Incompatibility with Majrusz Difficulty

### ISSUE THREAD

**Issue by FLSoz** [sisby-folk/tinkerers-smithing#30]
Fabric 1.20.1

![image](https://github.com/sisby-folk/tinkerers-smithing/assets/65517812/27277684-6b12-4d85-a5cc-98423c80664a)
sample log: https://mclo.gs/GllhrFf

It's crashing here: https://github.com/sisby-folk/tinkerers-smithing/blob/46db139f9236992501f8b763a42f301f95448e33/src/main/java/folk/sisby/tinkerers_smithing/TinkerersSmithingLoader.java#L282

Likely because of Majrusz setting name to client only fsr: https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/blob/544a629793cfb2fb7e18107408259646aad48603/common/src/main/java/com/majruszsdifficulty/items/CustomArmorMaterial.java#L96

Opened a issue over there: https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/issues/205

In the meantime, can a fallback be added since the line in question is supposed to be debug text, and shouldn't be failing?

**Comment by sisby-folk** [comment]
Yeah that's on them - they developed that annotation and they put it on something you're absolutely allowed to call from the server. Won't add a try just because it's logging - that would potentially hide important errors.
