### ISSUE TITLE
Incompatibility with PushToCraft - recipeId is null

### ISSUE THREAD

**Issue by ConqAra** [sisby-folk/tinkerers-smithing#35]
Not able to run the mod with any versions that are 2.6.0+ (2.5.1 works just fine with my modpack)

Log: [https://mclo.gs/y6sWPDf](https://mclo.gs/y6sWPDf)

**Comment by sisby-folk** [comment]
You'll have to bisect for this one, but the stack indicates it might be an issue with pushtocraft - can you check if it occurs without it?

**Comment by ConqAra** [comment]
Ah, its compatibility issue with [Bouncy Life](https://beta.modrinth.com/mod/bouncy-life)
Ran fine when I removed it, I wonder why that's the case though? Odd.

**Comment by sisby-folk** [comment]
bouncy life includes pushtocraft, which seems to have the issue.

**Comment by sisby-folk** [comment]
I've reviewed this more extensively - We're calling `Ingredient.fromJson()`, which hits one of PushToCraft's hooks. That then expects a recipe ID to be not null, but our code is running before recipes are loaded, which is probably causing that to be not so.

Pushtocraft needs to add a null check - your log should provide plenty of context, so feel free to refile there.
