### ISSUE TITLE
Problem with downloading mod on modrinth/github

### ISSUE THREAD

**Issue by ConqAra** [sisby-folk/tinkerers-smithing#36]
![image](https://github.com/sisby-folk/tinkerers-smithing/assets/76233356/6abaffc6-95ad-49d1-bd10-586f01dc4adf)
I don't know why I'm getting a trojan warning when downloading your mod from https://modrinth.com/mod/tinkerers-smithing/version/2.6.7+1.18 or the github release

I'm not accusing either, I am hard hard doubting windows defender here, but its so adamant on this decision. I've tried friends scanning it and downloading it themselves and sending it to me and I still get the same problem.
Note that I've NEVER gotten this issue before, even on curseforge.
This only applies specifically to this file. Any other file is completely fine. This is also pretty much a fresh computer too, so I don't know why this is happening

Is my computer just schizo for this one file or something?

**Comment by ConqAra** [comment]
Really weird false positive, it was extremely bizarre how only this specific version/file was doing this. It all seems okay otherwise. Just gonna close.

**Comment by sisby-folk** [comment]
weird! feel free to run a full system scan to be sure against fracturizer or anything.
