### ISSUE TITLE
Item Upgrade Override

### ISSUE THREAD

**Issue by Atsumachi** [sisby-folk/tinkerers-smithing#43]
I apologize in advance, but I couldn't find anywhere else to ask this information so I'm hoping to get some help here. I'm trying to add compatability with a mod (Paladins & Priests) for personal use and have the upgrade path set for the armors included in the mod. Currently, Tinkerer's sets the upgrade recipe to use gold ingots:
![image](https://github.com/sisby-folk/tinkerers-smithing/assets/89116003/3d016c3f-0cda-4ace-a75f-2d6dbff3bfca)
But I want to change the upgrade material from gold to ghast tears as that's the more important item of the original crafting recipe and I don't want to bypass acquiring the more difficult to obtain item:
![image](https://github.com/sisby-folk/tinkerers-smithing/assets/89116003/9dc801ea-ba94-40cc-ae0b-391cf9181873)
Is there any override that I can add to the fields (sorry if fields is the wrong word, I'm still trying to learn java) that will allow me to specify the ghast tear as the upgrade item instead of the gold?

**Comment by sisby-folk** [comment]
yep! datapackable:

`data/tinkerers_smithing/recipe/shapeless/paladins/prior_robe_head/paladins/priest_robe_head.json`
`data/tinkerers_smithing/recipe/smithing/paladins/prior_robe_head/paladins/priest_robe_head.json`

(yes, both)

```json
{
	"type": "tinkerers_smithing:shapeless",
	"base": "paladins:priest_robe_head"
	"addition": {
		"item": "minecraft:ghast_tear"
	}
	"additionCount": 1
	"result": "paladins:prior_robe_head"
}
```

if i got the items wrong, just swap out the ids

**Comment by Atsumachi** [comment]
Oh I'm so dumb, I completely forgot about adding the recipes. Thank you very much!
