### ISSUE TITLE
item repair feature breaks with AlmostUnified

### ISSUE THREAD

**Issue by RubyRed404** [sisby-folk/tinkerers-smithing#48]
The item repair feature using raw material costs (eg.: iron helmet + iron ingot) is non-functional with the mod [AlmostUnified](https://modrinth.com/mod/almost-unified) installed
expected behavior (**without** [AlmostUnified](https://modrinth.com/mod/almost-unified) installed):
![image](https://github.com/user-attachments/assets/7f4ad934-4980-49da-a67f-26d5252d7020)
actual behavior (**with** [AlmostUnified](https://modrinth.com/mod/almost-unified) installed):
![image](https://github.com/user-attachments/assets/3dfdd8a5-8796-43e4-9d09-05357300d3f2)

This does **NOT** apply when repairing an item with an **identical** copy of itself (eg.: iron helmet + another iron helmet)
In this case it seems to behave as expected both with and without the mod installed.

[EMI](https://modrinth.com/mod/emi) recipe still shows up in both cases (both without and with the mod installed):
![image](https://github.com/user-attachments/assets/5da82fbf-9727-4907-a552-c9e1b5e533b0)

**Comment by RubyRed404** [comment]
Now that I'm thinking more about it, I did not test having ONLY AlmostUnified and TinkerersSmithin installed, and taking into the account the nature of AlmostUnified this incorrect behavior might actually only show up if another mod modifies/has conflicting recipes with this mod. What I don't understand is that to my knowledge that  should only overwrite, not delete a particular recipe, which it seemingly does here.
The item + raw resource recipe seems to just get completely removed, not just overwritten...
Disclaimer: I am not one bit familiar with minecraft modding in general. I am currently solely a consumer, not creator, of mods.

**Comment by sisby-folk** [comment]
Tinkerer's Smithing adds some pretty basic recipes, so I'm guessing what's happening is that recipe discovery is failing due to this unification mod replacing recipe ingredients with tags (TSmithing *needs* real non-tag ingredients, or it will fail)

TSmithing comes with a config (config/tinkerer's_smithing.toml) for manually specifying substitutes that mods like this are doing, so setting that up is just the price of a magic bullet ingredient replacement mod in general.

**Comment by RubyRed404** [comment]
I see... I was *just* reading the [AlmostUnified wiki](https://github.com/AlmostReliable/almostunified/wiki) actually trying to figure out something to maybe configure for it to work nicer with TSmithing, something like telling AU to put the recipes added by this mod to some kinda blacklist to not touch them.

Based on what you said I'm assuming that in order to make a compatibility fix I'd need to add as you said the tag substitutions in the .toml file. Problem is, I have no idea where I could find a list of tags that this mod generates. I have no context on what AU internally calls the tags that it adds/modifies to the recipes. Could be "AU:gold", "AUnified:gold", or "AlmostUnified:gold_materials" for all I know...
...That, and if it is somehow procedurally generated in any way, I'd basically have a forever uphill battle on my hands trying to find every single material it touches and replaces with its own tag from every single mod on the planet.

Hmm... I'm not quite sure where to go with this... I'll probably just disable AU for the time being. Thank you for the help and extremely quick response tho! 
I don't expect you to fix this, as its clearly not a fault of this mod, but rather an unfortunate side effect of how both mods work fundamentally, so don't feel pressures or anything, I'm just glad I now understand a little better what exactly is going on.

**Comment by sisby-folk** [comment]
yeah it's a tricky case where Tinkerer's Smithing is scanning the base recipes that AU is modifying - so it's not even about the recipes this mod adds. I'll mark this as not planned!
