### ISSUE TITLE
Help with compatibility datapack creation

### ISSUE THREAD

**Issue by JotaFaD** [sisby-folk/tinkerers-smithing#54]
I'm creating a datapack to add compatility between this mod and [Basic Weapons](https://www.curseforge.com/minecraft/mc-mods/basic-weapons), which adds Daggers, Hammers, Clubs, Spears, Staffs and Glaives. I followed the structure [here](https://github.com/sisby-folk/tinkerers-quilt/tree/1.19_modded/resources/datapacks/tinkerers_smithing_farmersdelight) and **got most weapons to work, with the exception of the Daggers**.

Below is the file for glaives, which as you can see by the screenshot, are working.

```json
tinkerers_smithing_basic_weapons\data\basicweapons\smithing_types\glaive.json
{
  "replace": false,
  "values": [
    "#c:tools/glaives"
  ]
}
```
![image](https://github.com/user-attachments/assets/c582c2d3-8fdd-48bd-ba4a-1dec544ee570)

And now the files for the daggers, which looks exactly the same, but doesn't work in game.
```json
tinkerers_smithing_basic_weapons\data\basicweapons\smithing_types\dagger.json
{
  "replace": false,
  "values": [
    "#c:tools/daggers"
  ]
}
```

Strangely, I also tried creating a datapack for farmer's delight by copying the files in the source I linked above, but got the same problem with the knives. They don't work in-game.

I'm including my datapacks if you want to take a look. Any help is much appreciated.

[datapacks.zip](https://github.com/user-attachments/files/17499153/datapacks.zip)

**Comment by sisby-folk** [comment]
![image](https://github.com/user-attachments/assets/b88631ec-bed2-4558-af44-7cbfe3399db7)

your datapack works for me just fine!

![image](https://github.com/user-attachments/assets/81a43844-9217-4c7f-a522-27537e3cb75c)

no issues in the log either - don't forget to manually add diamond unit costs for netherite items! you can see how [here!](https://github.com/sisby-folk/tinkerers-smithing/tree/1.19/src/main/resources/data/minecraft/smithing_unit_costs)

**Comment by sisby-folk** [comment]
Feel free to follow up with more info and we'll happily help out, i'm just keeping the tracker clean.
