### ISSUE TITLE
Partially incompatible with BCLib

### ISSUE THREAD

**Issue by SplendidAlakey** [sisby-folk/tinkerers-smithing#7]
**MC** 1.19.2
**QSL** 4.0.0-beta.16
**Tinkerer's Smithing** 1.0.1 (the problem exists on 1.0.0 as well)
**[BCLib](https://www.curseforge.com/minecraft/mc-mods/bclib)** 2.1.2

When both mods are present, the smithing table changes don't apply, but everything else works as intended.
![2022-10-23_14 41 39](https://user-images.githubusercontent.com/86702831/197392950-a1232217-9d2c-400e-ae9f-0b0fa1ee1f53.png)

There's [another mod](https://www.curseforge.com/minecraft/mc-mods/actually-useful-smithing-table-fabric) that changes what tools can be upgraded at the smithing table and that one works with BCLib, so reporting here first. Let me know if this needs to be reported to BCLib.

Logs: https://gist.github.com/SplendidAlakey/f6140570eec4af29dc28654093443d74

**Comment by sisby-folk** [comment]
Tinkerer's Smithing isn't a unique mod - it's just a datapack for NBTcrafting 2 - to that end, I'd specifically report an incompatibility between "nbt crafting smithing recipes" and BCLib, to BCLib (and nbt crafting too, if you like).

**Comment by lxly9** [comment]
anvil recipes also do not work and bclib hasnt been updated since nor ahs it addressed the issue ;/

**Comment by SplendidAlakey** [comment]
@lxly9 seems like they have? https://github.com/quiqueck/BCLib/issues/45 + https://github.com/quiqueck/BetterEnd/issues/64

**Comment by Gredys** [comment]
> @lxly9 seems like they have? [quiqueck/BCLib#45](https://github.com/quiqueck/BCLib/issues/45) + [quiqueck/BetterEnd#64](https://github.com/quiqueck/BetterEnd/issues/64)

The problem still exists, while their issues are fixed.

Maybe its time to really dig up in this situation and check why its not worling like intended?

The mod is not usable in any way with most latest mod packs :/

**Comment by sisby-folk** [comment]
There's nothing really I can do about this one, please do make an issue on NBT crafting or BetterEnd's github issue page.

**Comment by Gredys** [comment]
> There's nothing really I can do about this one, please do make an issue on NBT crafting or BetterEnd's github issue page.

How can we detect the source of the problem without debugging the mod?

Creating the ticket on their side with message like "The mod X is not working cos of your mod Y and you need to fix this is issue on your side" won't work without any usefull information, cos they are not developing your mod.

Mod owners, for most time, are talking with each other to fix compability issues like this one and not making users to talk for them :/

**Comment by sisby-folk** [comment]
it's not my mod, genuinely. this is just a datapack. I don't know how nbtc
works internally I just write recipes.
